### ISSUE TITLE
[question] Callback URL?

### ISSUE THREAD

**Issue by lceberg** [cynical89/dev-portal#1]
You probably did not expect issues that early. :D

I'm most likely missing something, but I tried to run the application on http://localhost:5000/ , which worked fine. However upon clicking the "Sign in with Github" button I get "redirect_uri_mismatch" error.

I've added the clientID and clientSecret to config.json, but I'm not sure what should I add under "Authorization callback URL" in the GitHub app.

I tried empty value, http://localhost:5000/ and http://localhost:5000/auth/github/callback
If I'm not logged in (in GitHub) I get the  ability to log in, but I get the same error afterwards.

**Comment by cynical89** [comment]
comment out this line https://github.com/cynical89/dev-portal/blob/master/models/auth.js#L27

and then uncomment this line https://github.com/cynical89/dev-portal/blob/master/models/auth.js#L28

Then on github use http://localhost:5000/auth/github/callback for your call back and it should work. I swapped them because it's online on a webserver being tested

**Comment by lceberg** [comment]
That fixed it, thanks!
